stages:
  - build
  - deploy

variables:
  IMAGE_TAG: "wushie/test:$CI_COMMIT_SHA"

build:
  stage: build
  image: docker:20
  services:
    - docker:20-dind
  before_script:
    - docker login -u "DOCKER_USER" -p "DOCKER_PASSWORD"
  script:
    - docker pull $IMAGE_TAG || true
    - docker build --cache-from $IMAGE_TAG --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG

  rules:
    - changes:
        - Dockerfile
        - "**/*.go"

deploy:
  stage: deploy
  image: alpine/k8s:1.28.13
  script:
    - kubectl get pod
    - kubectl apply -f test.yaml

  only:
    - main

